[config]
name = "macOS"

[config.js]
module = '''
import buildMenuHandler from 'dist/menu.js';
export const menu = buildMenuHandler(import.meta);
'''

[chords]
'?/' = { name = "Global Apps" }

'?\' = { name = "System Apps/Shortucts"}
'\f' = { name = "Finder", shell = "open -a Finder" }
'\q' = { name = "Force Quit", shortcut = "opt+cmd+esc" }
'\ls' = { name = "Lock Screen", shortcut = "opt+cmd+esc" }
'\lo' = { name = "Log Out", shortcut = "ctrl+cmd+q" }
'\lq' = { name = "Log Quit", shortcut = "opt+shift+cmd+q" }

'?\b' = { name = "Brightness"}
'\bu' = { name = "Brightness Up", shortcut = "BrightnessUp" }
'\bd' = { name = "Brightness Down", shortcut = "BrightnessDown" }

'?\v' = { name = "Volume"}
'\vu' = { name = "Volume Up", shortcut = "AudioVolumeUp" }
'\vd' = { name = "Volume Down", shortcut = "AudioVolumeDown" }
'\vm' = { name = "Volume Mute", shortcut = "AudioVolumeMute" }

# Comma because `Comma`nd
# The comma is a special "global key" because it can be overriden by apps (for example, if an app uses cmd+shift+z instead of cmd+y for undo).
'?,' = { name = "Universal Commands" }
',a' = { name = "Select All", shortcut = "cmd+a" }
',s' = { name = "Save", shortcut = "cmd+s" }
',f' = { name = "Find", shortcut = "cmd+f" }
',r' = { name = "Refresh", shortcut = "cmd+r" }
',z' = { name = "Undo", shortcut = "cmd+z" }
',y' = { name = "Redo", shortcut = "cmd+y" }
',x' = { name = "Cut", shortcut = "cmd+x" }
',c' = { name = "Copy", shortcut = "cmd+c" }
',v' = { name = "Paste", shortcut = "cmd+v" }
',o' = { name = "Open", shortcut = "cmd+o" }
',n' = { name = "New", shortcut = "cmd+n" }
',m' = { name = "Minimize", shortcut = "cmd+m" }
',[' = { name = "Back", shortcut = "cmd+[" }
',]' = { name = "Forward", shortcut = "cmd+]" }
',q' = { name = "Quit", shortcut = "cmd+q" }
',w' = { name = "Close", shortcut = "cmd+w" }
',,' = { name = "Settings", shortcut = "cmd+," }

'?-' = { name = "Menu Bar" }
'-0' = { name = "Menu Bar: Apple Icon", 'args:menu' = [0] }
'-1' = { name = "Menu Bar: Item 1", 'args:menu' = [1] }
'-2' = { name = "Menu Bar: Item 2", 'args:menu' = [2] }
'-3' = { name = "Menu Bar: Item 3", 'args:menu' = [3] }
'-4' = { name = "Menu Bar: Item 4", 'args:menu' = [4] }
'-5' = { name = "Menu Bar: Item 5", 'args:menu' = [5] }
'-6' = { name = "Menu Bar: Item 6", 'args:menu' = [6] }
'-7' = { name = "Menu Bar: Item 7", 'args:menu' = [7] }
'-8' = { name = "Menu Bar: Item 8", 'args:menu' = [8] }
'-9' = { name = "Menu Bar: Item 9", 'args:menu' = [9] }

'?=' = { name = "Tray" }
'=1' = { name = "Tray: Item 1" }
'=2' = { name = "Tray: Item 2" }
'=3' = { name = "Tray: Item 3" }
'=4' = { name = "Tray: Item 4" }
'=5' = { name = "Tray: Item 5" }
'=6' = { name = "Tray: Item 6" }
'=7' = { name = "Tray: Item 7" }
'=8' = { name = "Tray: Item 8" }
'=9' = { name = "Tray: Item 9" }
