[config]
name = "macOS"

[chords]
'?/' = { name = "Global Apps" }

'?\' = { name = "System Apps/Shortucts"}
'\f' = { name = "Finder", shell = "open -a Finder" }
'\q' = { name = "Force Quit", shortcut = "opt+cmd+esc" }
'\ls' = { name = "Lock Screen", shortcut = "opt+cmd+esc" }
'\lo' = { name = "Log Out", shortcut = "ctrl+cmd+q" }
'\lq' = { name = "Log Quit", shortcut = "opt+shift+cmd+q" }

'?\b' = { name = "Brightness"}
'\bu' = { name = "Brightness Up", shortcut = "BrightnessUp" }
'\bd' = { name = "Brightness Down", shortcut = "BrightnessDown" }

'?\v' = { name = "Volume"}
'\vu' = { name = "Volume Up", shortcut = "AudioVolumeUp" }
'\vd' = { name = "Volume Down", shortcut = "AudioVolumeDown" }
'\vm' = { name = "Volume Mute", shortcut = "AudioVolumeMute" }

# Comma because `Comma`nd
# The comma is a special "global key" because it can be overriden by apps (for example, if an app uses cmd+shift+z instead of cmd+y for undo).
'?,' = { name = "Universal Commands" }
',a' = { name = "Select All", shortcut = "cmd+a" }
',s' = { name = "Save", shortcut = "cmd+s" }
',f' = { name = "Find", shortcut = "cmd+f" }
',r' = { name = "Refresh", shortcut = "cmd+r" }
',z' = { name = "Undo", shortcut = "cmd+z" }
',y' = { name = "Redo", shortcut = "cmd+y" }
',x' = { name = "Cut", shortcut = "cmd+x" }
',c' = { name = "Copy", shortcut = "cmd+c" }
',v' = { name = "Paste", shortcut = "cmd+v" }
',o' = { name = "Open", shortcut = "cmd+o" }
',n' = { name = "New", shortcut = "cmd+n" }
',m' = { name = "Minimize", shortcut = "cmd+m" }
',[' = { name = "Back", shortcut = "cmd+[" }
',]' = { name = "Forward", shortcut = "cmd+]" }
',q' = { name = "Quit", shortcut = "cmd+q" }
',w' = { name = "Close", shortcut = "cmd+w" }
',,' = { name = "Settings", shortcut = "cmd+," }
