[config]
name = "Windows"

[config.js]
module = '''
import buildMenuHandler from 'dist/menu.js';
export const menu = buildMenuHandler();
'''

[chords]
'?/' = { name = "Global Apps" }

# Comma because `Comma`nd
# The comma is a special "global key" because it can be overriden by apps (for example, if an app uses cmd+shift+z instead of cmd+y for undo).
# We define these "universal shortcuts" so that they work cross-platform (ctrl on Windows, cmd on macOS), and so we don't need to redefine them in every app
'?,' = { name = "Universal Commands" }
',a' = { name = "Select All", shortcut = "ctrl+a" }
',s' = { name = "Save", shortcut = "ctrl+s" }
',f' = { name = "Find", shortcut = "ctrl+f" }
',h' = { name = "Hide", shortcut = "ctrl+h" }
',r' = { name = "Refresh", shortcut = "ctrl+r" }
',z' = { name = "Undo", shortcut = "ctrl+z" }
',y' = { name = "Redo", shortcut = "ctrl+y" }
',x' = { name = "Cut", shortcut = "ctrl+x" }
',c' = { name = "Copy", shortcut = "ctrl+c" }
',v' = { name = "Paste", shortcut = "ctrl+v" }
',o' = { name = "Open", shortcut = "ctrl+o" }
',n' = { name = "New", shortcut = "ctrl+n" }
',m' = { name = "Minimize", shortcut = "ctrl+m" }
',[' = { name = "Back", shortcut = "ctrl+[" }
',]' = { name = "Forward", shortcut = "ctrl+]" }
',q' = { name = "Quit", shortcut = "ctrl+q" }
',w' = { name = "Close", shortcut = "ctrl+w" }
',,' = { name = "Settings", shortcut = "ctrl+," }
',=' = { name = "Zoom In", shortcut = "ctrl+=" }
',-' = { name = "Zoom Out", shortcut = "ctrl+-" }
