[config]
name = "Chords"

[chords]
# A shortcut that likely won't conflict with any user-defined chords.
'?\\' = { name = "Chords" }

'\\s' = { name = "Settings" }
'\\r' = { name = "Reload Config" }
'\\q' = { name = "Quit Chord" }
